apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  annotations:
    appstudio.openshift.io/application: appstudio
    appstudio.openshift.io/component: dc-metro-map
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: dc-metro-map
  namespace: 6f28ad7d-8723-450c-82a3-91bb96013e77
spec:
  git_provider:
    secret:
      key: github.token
      name: pipelines-as-code-secret
    webhook_secret:
      key: https___github.com_scoheb_dc-metro-map
      name: pipelines-as-code-webhooks-secret
  url: https://github.com/scoheb/dc-metro-map
